version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: devquizhub
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: devquizhub
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    ports:
      - "3307:3306"
    networks:
      - devquizhub

#  backend:
#    container_name: backend
#    build: ./backend/
#    ports:
#      - "8080:8080"
#    environment:
#      WAIT_HOSTS: mysql:3306
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devquizhub?createDatabaseIfNotExist=true&characterEncoding=UTF-8&profileSql=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#      SPRING_DATASOURCE_USERNAME: devquizhub
#      SPRING_DATASOURCE_PASSWORD: 1234
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    depends_on:
#      - mysql
#    networks:
#      - devquizhub

#  frontend:
#    container_name: "frontend"
#    build:
#      context: ./frontend
#    ports:
#      - "3000:3000"

networks:
  devquizhub:
    driver: bridge