
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/devquizhub?createDatabaseIfNotExist=true&characterEncoding=UTF-8&profileSql=true
    username: devquizhub
    password: 1234

  jpa:
    hibernate:
      ddl-auto : create #update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show_sql: true

logging:
  level:
    org:
      hibernate: info
